import os
from jinja2 import Template
from typing import List, Dict

TEMPLATE_MD = """
# Vulnerability Report

Scanned file: {{ file }}

## Summary

- Total findings: {{ total }}
- Top severity: {{ top_severity }}

## Findings (ranked)

{% for f in findings %}
- **Severity:** {{ f.severity }} — **Type:** {{ f.type }} — **Line:** {{ f.lineno }}
  - Message: {{ f.message }}
{% endfor %}

## Notes

This report is generated by Haris — review findings and remediate accordingly.
"""


def generate_markdown_report(file: str, findings: List[Dict], ranked: List[Dict], out_path: str):
    ctx = {
        'file': file,
        'findings': ranked,
        'total': len(findings),
        'top_severity': ranked[0]['severity'] if ranked else 'None'
    }
    tpl = Template(TEMPLATE_MD)
    md = tpl.render(**ctx)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write(md)
    return out_path
